project_id = "ucqcrhfcflrepsdlcvpq"

[functions.add-quest-courses]
verify_jwt = false

[functions.generate-nft-character]
verify_jwt = true

[functions.fetch-user-nfts]
verify_jwt = true

[functions.sync-farcaster-profile]
verify_jwt = false

[functions.share-to-farcaster]
verify_jwt = true

[functions.create-course-payment-frame]
verify_jwt = true

[functions.create-nft-purchase-frame]
verify_jwt = true

[functions.verify-course-payment]
verify_jwt = false

[functions.verify-nft-purchase]
verify_jwt = false

[functions.process-checkin]
verify_jwt = true

[functions.process-transaction-with-fees]
verify_jwt = true

[functions.verify-farcaster-follow]
verify_jwt = true

[functions.complete-task]
verify_jwt = true

[functions.fetch-farcaster-wallet]
verify_jwt = true

[functions.farcaster-frame]
verify_jwt = false

[functions.uniqbot-chat]
verify_jwt = false

[functions.miniapp-webhook]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = true

[functions.fetch-farcaster-balances]
verify_jwt = true

[functions.farcaster-mention-handler]
verify_jwt = false

