[package]
name = "multichain-rewards-claim"
version = "0.1.0"
description = "Solana program for claiming daily token rewards based on user points"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "multichain_rewards_claim"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
