-- Add 3 new courses to learning hub: Crypto Wallet, Blockchain, and NFTs

-- Insert the 3 new courses
INSERT INTO public.learning_courses (title, description, category, total_modules, difficulty_level, is_active)
VALUES 
  ('How to Use a Crypto Wallet', 'Learn the fundamentals of crypto wallets, from creating your first wallet to keeping it secure.', 'wallet', 10, 'beginner', true),
  ('Blockchain for Beginners', 'Understand how blockchain technology works, from blocks and nodes to smart contracts and DApps.', 'blockchain', 10, 'beginner', true),
  ('NFTs Basics', 'Discover the world of NFTs, from art and gaming to collectibles and real-world applications.', 'nft', 10, 'beginner', true);

-- Insert modules for "How to Use a Crypto Wallet"
INSERT INTO public.learning_modules (course_id, module_number, title, description, content, points_reward, is_locked)
SELECT 
  c.id,
  module_data.module_number,
  module_data.title,
  module_data.description,
  module_data.content,
  10,
  CASE WHEN module_data.module_number = 1 THEN false ELSE true END
FROM public.learning_courses c,
LATERAL (VALUES
  (1, 'What is a Crypto Wallet', 'A crypto wallet stores digital money and NFTs. It lets you send, receive, and check your balance.', '{"text": "A crypto wallet stores digital money and NFTs. It lets you send, receive, and check your balance.", "quiz": [{"question": "A crypto wallet stores:", "options": ["Digital money", "Cash", "Gold"], "correct": 0}, {"question": "Wallets let you:", "options": ["Send crypto", "Receive crypto", "Check balance", "All of the above"], "correct": 3}, {"question": "A wallet can be:", "options": ["Physical", "Digital", "Both A and B"], "correct": 2}]}'::jsonb),
  (2, 'Types of Wallets', 'Hot wallets are connected to the internet. Cold wallets are offline and more secure.', '{"text": "Hot wallets are connected to the internet. Cold wallets are offline and more secure.", "quiz": [{"question": "Hot wallets are:", "options": ["Online", "Offline", "Paper only"], "correct": 0}, {"question": "Cold wallets are:", "options": ["Online", "Offline", "Software only"], "correct": 1}, {"question": "Which is safer?", "options": ["Hot wallet", "Cold wallet", "Both same"], "correct": 1}]}'::jsonb),
  (3, 'Creating a Wallet', 'You can create a wallet using apps like MetaMask or Trust Wallet. Follow instructions and save your seed phrase.', '{"text": "You can create a wallet using apps like MetaMask or Trust Wallet. Follow instructions and save your seed phrase.", "quiz": [{"question": "To create a wallet, use:", "options": ["A crypto app", "Bank", "Browser"], "correct": 0}, {"question": "What must you save carefully?", "options": ["Seed phrase", "Password only", "Email"], "correct": 0}, {"question": "Seed phrase is:", "options": ["Secret", "Public", "Optional"], "correct": 0}]}'::jsonb),
  (4, 'Seed Phrase Safety', 'Never share your seed phrase. Anyone with it can access your funds. Write it down and store safely offline.', '{"text": "Never share your seed phrase. Anyone with it can access your funds. Write it down and store safely offline.", "quiz": [{"question": "Seed phrase should be:", "options": ["Shared with friends", "Kept secret", "Posted online"], "correct": 1}, {"question": "What happens if someone gets your seed phrase?", "options": ["Nothing", "They can steal your crypto", "They can only view balance"], "correct": 1}, {"question": "Best way to store seed phrase:", "options": ["Online notes", "Paper offline", "Cloud"], "correct": 1}]}'::jsonb),
  (5, 'Receiving Crypto', 'To receive crypto, share your wallet address. Always double-check it before sending.', '{"text": "To receive crypto, share your wallet address. Always double-check it before sending.", "quiz": [{"question": "To receive crypto, you need:", "options": ["Email", "Wallet address", "Phone number"], "correct": 1}, {"question": "Always:", "options": ["Check address", "Ignore mistakes", "Share publicly"], "correct": 0}, {"question": "Wallet address is:", "options": ["Unique", "Shared with everyone", "Random"], "correct": 0}]}'::jsonb),
  (6, 'Sending Crypto', 'Enter recipient''s address, choose amount, and confirm. Always verify the address to avoid mistakes.', '{"text": "Enter recipient''s address, choose amount, and confirm. Always verify the address to avoid mistakes.", "quiz": [{"question": "To send crypto, you need:", "options": ["Recipient address", "Password only", "Email"], "correct": 0}, {"question": "Before sending, check:", "options": ["Recipient address", "Amount", "Both A and B"], "correct": 2}, {"question": "Crypto transactions are:", "options": ["Reversible", "Permanent", "Optional"], "correct": 1}]}'::jsonb),
  (7, 'Wallet Backup', 'Backup your wallet by saving the seed phrase in a secure place. Without it, you can lose access to funds.', '{"text": "Backup your wallet by saving the seed phrase in a secure place. Without it, you can lose access to funds.", "quiz": [{"question": "What do you backup?", "options": ["Seed phrase", "Password only", "Email"], "correct": 0}, {"question": "Why backup is important?", "options": ["For fun", "To prevent losing funds", "Optional"], "correct": 1}, {"question": "Best backup storage:", "options": ["Paper offline", "Cloud", "Email"], "correct": 0}]}'::jsonb),
  (8, 'Avoiding Scams', 'Never click suspicious links or give your private key. Scammers often pretend to help.', '{"text": "Never click suspicious links or give your private key. Scammers often pretend to help.", "quiz": [{"question": "Should you share your private key?", "options": ["Yes", "No"], "correct": 1}, {"question": "Phishing links are:", "options": ["Safe", "Dangerous", "Optional"], "correct": 1}, {"question": "Scammers may:", "options": ["Pretend to help", "Steal crypto", "Both A and B"], "correct": 2}]}'::jsonb),
  (9, 'Checking Your Balance', 'Open your wallet app to check balance. Some wallets also show NFT holdings and transaction history.', '{"text": "Open your wallet app to check balance. Some wallets also show NFT holdings and transaction history.", "quiz": [{"question": "Wallet apps show:", "options": ["Balance", "NFTs", "Transaction history", "All of the above"], "correct": 3}, {"question": "Checking balance helps you:", "options": ["Track spending", "Confirm transactions", "Both A and B"], "correct": 2}, {"question": "NFT holdings can be:", "options": ["Digital art", "Tokens", "Both A and B"], "correct": 2}]}'::jsonb),
  (10, 'Real-World Wallet Uses', 'Wallets let you pay for services, trade crypto, interact with DApps, and hold NFTs.', '{"text": "Wallets let you pay for services, trade crypto, interact with DApps, and hold NFTs.", "quiz": [{"question": "Wallets can be used for:", "options": ["Paying for services", "Trading crypto", "Holding NFTs", "All of the above"], "correct": 3}, {"question": "DApps interact with:", "options": ["Wallet", "Bank", "Mobile only"], "correct": 0}, {"question": "Wallets are:", "options": ["Only for crypto", "For digital assets", "Physical money"], "correct": 1}]}'::jsonb)
) AS module_data(module_number, title, description, content)
WHERE c.title = 'How to Use a Crypto Wallet';

-- Insert modules for "Blockchain for Beginners"
INSERT INTO public.learning_modules (course_id, module_number, title, description, content, points_reward, is_locked)
SELECT 
  c.id,
  module_data.module_number,
  module_data.title,
  module_data.description,
  module_data.content,
  10,
  CASE WHEN module_data.module_number = 1 THEN false ELSE true END
FROM public.learning_courses c,
LATERAL (VALUES
  (1, 'What is a Block', 'A block is a package of data stored on a blockchain. Each block contains transactions and a reference to the previous block.', '{"text": "A block is a package of data stored on a blockchain. Each block contains transactions and a reference to the previous block.", "quiz": [{"question": "A block stores:", "options": ["Money only", "Data and transactions", "Nothing"], "correct": 1}, {"question": "Each block links to:", "options": ["A random block", "The previous block", "The next app"], "correct": 1}, {"question": "Blocks make blockchain:", "options": ["Secure", "Weak", "Invisible"], "correct": 0}]}'::jsonb),
  (2, 'What is a Node', 'Nodes are computers that store and verify blockchain data. They ensure the network works correctly.', '{"text": "Nodes are computers that store and verify blockchain data. They ensure the network works correctly.", "quiz": [{"question": "A node is:", "options": ["A computer on the blockchain", "A bank", "A mobile app"], "correct": 0}, {"question": "Nodes help:", "options": ["Verify transactions", "Store data", "Both A and B"], "correct": 2}, {"question": "Without nodes, blockchain:", "options": ["Works the same", "Can''t function", "Becomes faster"], "correct": 1}]}'::jsonb),
  (3, 'Consensus', 'Consensus is how blockchain agrees on transactions. Common methods: Proof of Work and Proof of Stake.', '{"text": "Consensus is how blockchain agrees on transactions. Common methods: Proof of Work and Proof of Stake.", "quiz": [{"question": "Consensus means:", "options": ["Everyone agrees", "Only the owner decides", "Random selection"], "correct": 0}, {"question": "Proof of Work involves:", "options": ["Mining", "Voting", "Coding only"], "correct": 0}, {"question": "Proof of Stake uses:", "options": ["Computers solving puzzles", "Coin ownership for validation", "Cash"], "correct": 1}]}'::jsonb),
  (4, 'Mining vs Staking', 'Mining solves complex puzzles to add blocks. Staking locks coins to validate transactions.', '{"text": "Mining solves complex puzzles to add blocks. Staking locks coins to validate transactions.", "quiz": [{"question": "Mining is:", "options": ["Manual work", "Solving puzzles to add blocks", "Sending emails"], "correct": 1}, {"question": "Staking is:", "options": ["Locking coins to validate transactions", "Mining", "Investing in stocks"], "correct": 0}, {"question": "Both mining and staking:", "options": ["Help secure blockchain", "Are optional", "Are scams"], "correct": 0}]}'::jsonb),
  (5, 'Security in Blockchain', 'Blockchain is secure because data is encrypted, decentralized, and immutable.', '{"text": "Blockchain is secure because data is encrypted, decentralized, and immutable.", "quiz": [{"question": "Blockchain is secure because:", "options": ["Data is encrypted", "Decentralized", "Immutable", "All of the above"], "correct": 3}, {"question": "Immutable means:", "options": ["Can be changed", "Cannot be changed", "Invisible"], "correct": 1}, {"question": "Decentralization means:", "options": ["One company controls it", "No single control", "Everyone owns a bank"], "correct": 1}]}'::jsonb),
  (6, 'Transactions', 'Blockchain transactions are verified by nodes, recorded in blocks, and cannot be changed once added.', '{"text": "Blockchain transactions are verified by nodes, recorded in blocks, and cannot be changed once added.", "quiz": [{"question": "Who verifies blockchain transactions?", "options": ["Nodes", "Banks", "Governments"], "correct": 0}, {"question": "Transactions are:", "options": ["Permanent", "Temporary", "Optional"], "correct": 0}, {"question": "Transactions are stored in:", "options": ["Wallets", "Blocks", "Apps"], "correct": 1}]}'::jsonb),
  (7, 'Smart Contracts', 'Smart contracts are self-executing programs on blockchain. They run when conditions are met, without intermediaries.', '{"text": "Smart contracts are self-executing programs on blockchain. They run when conditions are met, without intermediaries.", "quiz": [{"question": "Smart contracts run:", "options": ["Manually", "Automatically", "Never"], "correct": 1}, {"question": "They remove the need for:", "options": ["Banks", "Intermediaries", "Apps", "Both A and B"], "correct": 3}, {"question": "Smart contracts are stored on:", "options": ["Blockchain", "Cloud only", "Mobile"], "correct": 0}]}'::jsonb),
  (8, 'Decentralized Apps (DApps)', 'DApps are applications that run on blockchain. They are decentralized and trustless.', '{"text": "DApps are applications that run on blockchain. They are decentralized and trustless.", "quiz": [{"question": "DApp stands for:", "options": ["Digital App", "Decentralized App", "Data App"], "correct": 1}, {"question": "DApps are controlled by:", "options": ["No central authority", "CEO", "Government"], "correct": 0}, {"question": "DApps use:", "options": ["Blockchain", "Internet only", "USB"], "correct": 0}]}'::jsonb),
  (9, 'Real-World Blockchain Uses', 'Blockchain is used in finance (DeFi), supply chain, voting, NFTs, and gaming.', '{"text": "Blockchain is used in finance (DeFi), supply chain, voting, NFTs, and gaming.", "quiz": [{"question": "Blockchain can be used in:", "options": ["Finance", "Voting", "Gaming", "All of the above"], "correct": 3}, {"question": "NFTs are:", "options": ["Unique digital items", "Cash", "Apps"], "correct": 0}, {"question": "DeFi is:", "options": ["Centralized finance", "Decentralized finance", "Cloud storage"], "correct": 1}]}'::jsonb),
  (10, 'Blockchain Summary', 'Blockchain is a secure, decentralized ledger of blocks. It powers crypto, NFTs, smart contracts, and DApps.', '{"text": "Blockchain is a secure, decentralized ledger of blocks. It powers crypto, NFTs, smart contracts, and DApps.", "quiz": [{"question": "Blockchain is:", "options": ["Centralized", "Decentralized", "Random"], "correct": 1}, {"question": "What does blockchain power?", "options": ["Crypto", "NFTs", "DApps", "All of the above"], "correct": 3}, {"question": "Is blockchain secure?", "options": ["Yes", "No"], "correct": 0}]}'::jsonb)
) AS module_data(module_number, title, description, content)
WHERE c.title = 'Blockchain for Beginners';

-- Insert modules for "NFTs Basics"
INSERT INTO public.learning_modules (course_id, module_number, title, description, content, points_reward, is_locked)
SELECT 
  c.id,
  module_data.module_number,
  module_data.title,
  module_data.description,
  module_data.content,
  10,
  CASE WHEN module_data.module_number = 1 THEN false ELSE true END
FROM public.learning_courses c,
LATERAL (VALUES
  (1, 'What is an NFT', 'NFT stands for Non-Fungible Token. It is a unique digital asset stored on a blockchain.', '{"text": "NFT stands for Non-Fungible Token. It is a unique digital asset stored on a blockchain.", "quiz": [{"question": "NFT stands for:", "options": ["Non-Fungible Token", "New Fun Token", "Non-Financial Token"], "correct": 0}, {"question": "NFTs are:", "options": ["Identical", "Unique", "Fungible"], "correct": 1}, {"question": "NFTs are stored on:", "options": ["Blockchain", "Bank", "Cloud only"], "correct": 0}]}'::jsonb),
  (2, 'NFT Utility', 'NFTs can represent art, collectibles, tickets, or access rights. They give ownership and proof of authenticity.', '{"text": "NFTs can represent art, collectibles, tickets, or access rights. They give ownership and proof of authenticity.", "quiz": [{"question": "NFTs can represent:", "options": ["Art", "Tickets", "Collectibles", "All of the above"], "correct": 3}, {"question": "NFTs provide:", "options": ["Ownership", "Proof of authenticity", "Both A and B"], "correct": 2}, {"question": "NFTs are:", "options": ["Physical items", "Digital assets", "Paper certificates"], "correct": 1}]}'::jsonb),
  (3, 'Art NFTs', 'Art NFTs are digital artworks. They can be bought, sold, or displayed in virtual galleries.', '{"text": "Art NFTs are digital artworks. They can be bought, sold, or displayed in virtual galleries.", "quiz": [{"question": "Art NFTs are:", "options": ["Digital art", "Paintings only", "Photos only"], "correct": 0}, {"question": "You can:", "options": ["Buy them", "Sell them", "Display in virtual galleries", "All of the above"], "correct": 3}, {"question": "Ownership of an NFT means:", "options": ["You own the digital asset", "You own the original artwork", "Nothing"], "correct": 0}]}'::jsonb),
  (4, 'Gaming NFTs', 'Gaming NFTs give players unique in-game items. They can be traded or sold outside the game.', '{"text": "Gaming NFTs give players unique in-game items. They can be traded or sold outside the game.", "quiz": [{"question": "Gaming NFTs represent:", "options": ["Real money", "Unique in-game items", "Game codes only"], "correct": 1}, {"question": "Players can:", "options": ["Trade", "Sell", "Both A and B"], "correct": 2}, {"question": "Gaming NFTs are stored on:", "options": ["Blockchain", "Game server only", "Cloud"], "correct": 0}]}'::jsonb),
  (5, 'Collectibles', 'NFT collectibles are digital items you can collect, trade, or sell. Examples: CryptoPunks, Bored Ape Yacht Club.', '{"text": "NFT collectibles are digital items you can collect, trade, or sell. Examples: CryptoPunks, Bored Ape Yacht Club.", "quiz": [{"question": "Collectibles are:", "options": ["Digital items", "Only cards", "Coins"], "correct": 0}, {"question": "Examples of NFT collectibles:", "options": ["CryptoPunks", "Bored Ape Yacht Club", "Both A and B"], "correct": 2}, {"question": "You can:", "options": ["Collect", "Trade", "Sell", "All of the above"], "correct": 3}]}'::jsonb),
  (6, 'NFT Marketplaces', 'NFT marketplaces let you buy, sell, and mint NFTs. Examples: OpenSea, Rarible, Magic Eden.', '{"text": "NFT marketplaces let you buy, sell, and mint NFTs. Examples: OpenSea, Rarible, Magic Eden.", "quiz": [{"question": "NFT marketplaces allow you to:", "options": ["Buy NFTs", "Sell NFTs", "Mint NFTs", "All of the above"], "correct": 3}, {"question": "Examples of marketplaces:", "options": ["OpenSea", "Rarible", "Magic Eden", "All of the above"], "correct": 3}, {"question": "NFTs in marketplaces are:", "options": ["Digital assets", "Cash", "Tokens only"], "correct": 0}]}'::jsonb),
  (7, 'Minting NFTs', 'Minting means creating an NFT on the blockchain. Once minted, it is unique and owned by the creator or buyer.', '{"text": "Minting means creating an NFT on the blockchain. Once minted, it is unique and owned by the creator or buyer.", "quiz": [{"question": "Minting means:", "options": ["Creating an NFT", "Deleting an NFT", "Buying NFT only"], "correct": 0}, {"question": "Once minted, NFT is:", "options": ["Fungible", "Unique", "Random"], "correct": 1}, {"question": "NFT ownership goes to:", "options": ["Creator or buyer", "Marketplace", "Bank"], "correct": 0}]}'::jsonb),
  (8, 'NFT Value', 'NFT value depends on rarity, demand, and popularity. Some are worth thousands or millions of dollars.', '{"text": "NFT value depends on rarity, demand, and popularity. Some are worth thousands or millions of dollars.", "quiz": [{"question": "NFT value depends on:", "options": ["Rarity", "Demand", "Popularity", "All of the above"], "correct": 3}, {"question": "NFTs can be worth:", "options": ["A few dollars", "Thousands", "Millions", "All of the above"], "correct": 3}, {"question": "Popularity of an NFT:", "options": ["Increases value", "Decreases value", "No effect"], "correct": 0}]}'::jsonb),
  (9, 'Risks of NFTs', 'NFTs can lose value. Be cautious, avoid scams, and never invest more than you can afford to lose.', '{"text": "NFTs can lose value. Be cautious, avoid scams, and never invest more than you can afford to lose.", "quiz": [{"question": "NFT value can:", "options": ["Increase", "Decrease", "Both A and B"], "correct": 2}, {"question": "You should avoid:", "options": ["Scams", "Phishing links", "Both A and B"], "correct": 2}, {"question": "Invest only:", "options": ["What you can afford to lose", "Everything", "Randomly"], "correct": 0}]}'::jsonb),
  (10, 'Real-World NFT Uses', 'NFTs are used in art, music, gaming, fashion, tickets, and virtual real estate.', '{"text": "NFTs are used in art, music, gaming, fashion, tickets, and virtual real estate.", "quiz": [{"question": "NFTs can be used for:", "options": ["Art", "Music", "Gaming", "All of the above"], "correct": 3}, {"question": "Virtual real estate NFTs exist in:", "options": ["Metaverse", "Physical land", "Cloud only"], "correct": 0}, {"question": "NFT tickets allow:", "options": ["Proof of attendance", "Free money", "Nothing"], "correct": 0}]}'::jsonb)
) AS module_data(module_number, title, description, content)
WHERE c.title = 'NFTs Basics';